version: '3.8'

services:
  mailbomber:
    build: ./
    command: ./start.sh ./mailbomber
    depends_on:
      - db
    env_file:
      - configs/.env
    ports:
      - "8080:8080"

  db:
    restart: always
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mailbomber

  mailcatcher:
    restart: on-failure
    image: dockage/mailcatcher:0.9.0
    ports:
      - "1080:1080"
      - "1025:1025"